# Generated by Django 6.0.6 on 2026-09-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, default='India', max_length=100)),
                ('period', models.CharField(help_text='e.g. 2021 - 2024', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, default='Chennai, India', max_length=100)),
                ('period', models.CharField(help_text='e.g. May - June 2024', max_length=100)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Saritha N', max_length=100)),
                ('title', models.CharField(default='Python Full Stack Developer & Computer Science Undergraduate', max_length=200)),
                ('tagline', models.CharField(blank=True, default='Passionate about creating seamless user experiences and scalable server solutions.', max_length=255)),
                ('bio', models.TextField(default='I build complete web applications from frontend to backend using Python, Django, and modern JavaScript frameworks. Passionate about creating seamless user experiences and scalable server solutions.')),
                ('about_intro', models.TextField(default='A passionate Computer Science undergraduate with a strong foundation in web development and a drive to create innovative digital solutions. I specialize in building responsive, user-friendly websites using modern technologies.')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('availability_status', models.CharField(default='Available for opportunities', max_length=100)),
                ('email', models.EmailField(default='sarithasankari154@gmail.com', max_length=254)),
                ('phone', models.CharField(default='+91 93613 48040', max_length=30)),
                ('location', models.CharField(default='India', max_length=100)),
                ('degree', models.CharField(default='B.Sc CS', max_length=100)),
                ('university', models.CharField(default='Periyar University', max_length=150)),
                ('projects_count', models.CharField(default='5+', max_length=20)),
                ('certifications_count', models.CharField(default='9+', max_length=20)),
                ('technologies_count', models.CharField(default='20+', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=255)),
                ('icon_class', models.CharField(help_text="FontAwesome class e.g. 'fab fa-github'", max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='certification',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.CharField(help_text="Comma-separated tags e.g. 'Django, React, MySQL'", max_length=200),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Frontend', 'Frontend Development'), ('Backend', 'Backend Development'), ('Database', 'Database & Tools'), ('FE', 'Frontend Development'), ('BE', 'Backend Development'), ('DB', 'Database & Tools')], max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon_class',
            field=models.CharField(help_text="FontAwesome or Devicon class e.g., 'fab fa-python'", max_length=100),
        ),
    ]
